name: Build Flet APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install Flet
      run: pip install flet flet-cli

    - name: Build APK
      run: |
        flet build apk --module-name app
        find build -name "*.apk" -print
        ls -R build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: pixshare-apk
        path: build/app/outputs/flutter-apk/app-release.apk
